#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BLUETOOTH_QTI_SW TRUE

#define BTM_DEF_LOCAL_NAME   "Lenovo A6000"

#define MAX_ACL_CONNECTIONS 7

#define MAX_L2CAP_CHANNELS  16

#define BTA_SKIP_BLE_READ_REMOTE_FEAT TRUE

#define BTA_BLE_SKIP_CONN_UPD  TRUE

#endif
